package com.dyxia.nexuserp.service;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class QrCodeServiceTest {

    private final QrCodeService qrCodeService = new QrCodeService();

    @Test
    public void testGenerateEmployeeQrCode_Success() {
        String matricule = "E0001";
        
        byte[] qrCodeBytes = qrCodeService.generateEmployeeQrCode(matricule);
        
        // Assert that the generated byte array is not null and not empty
        assertNotNull(qrCodeBytes);
        assertTrue(qrCodeBytes.length > 0, "QR Code byte array should not be empty");

        // Verify the PNG magic header bytes: 89 50 4E 47 0D 0A 1A 0A
        // In signed bytes: -119, 80, 78, 71
        assertEquals((byte) 0x89, qrCodeBytes[0], "First byte of PNG header should match 0x89");
        assertEquals((byte) 0x50, qrCodeBytes[1], "Second byte of PNG header should match 'P'");
        assertEquals((byte) 0x4E, qrCodeBytes[2], "Third byte of PNG header should match 'N'");
        assertEquals((byte) 0x47, qrCodeBytes[3], "Fourth byte of PNG header should match 'G'");
    }

    @Test
    public void testGenerateEmployeeQrCode_InvalidMatriculeDoesNotThrow() {
        // ZXing should be able to encode any alphanumeric string matricule
        String matricule = "";
        byte[] qrCodeBytes = qrCodeService.generateEmployeeQrCode(matricule);
        
        assertNotNull(qrCodeBytes);
        assertTrue(qrCodeBytes.length > 0);
    }
}
