import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';

/**
 * Zustand store to manage and persist global authentication state.
 * Leverages localstorage persistence middleware to maintain session state across page reloads.
 */
const useAuthStore = create(
  persist(
    (set) => ({
      // --- State ---
      token: null,
      user: null,
      isAuthenticated: false,

      // --- Actions ---
      
      /**
       * Authenticates the user by saving the JWT access token and user metadata details.
       * 
       * @param {string} token - The secure JWT access token generated by the server.
       * @param {Object} user - The user details profile payload (id, email, firstName, lastName, roles, etc.).
       */
      login: (token, user) => set({
        token,
        user,
        isAuthenticated: true
      }),

      /**
       * Completely flushes the authentication state and terminates the active session.
       */
      logout: () => set({
        token: null,
        user: null,
        isAuthenticated: false
      }),
    }),
    {
      name: 'nexus-auth-storage', // Key used inside localstorage
      storage: createJSONStorage(() => localStorage), // Explicitly utilize standard localStorage wrapper
    }
  )
);

export default useAuthStore;
