spring:
  application:
    name: nexus-erp

  datasource:
    url: jdbc:mysql://localhost:3306/nexus_erp_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: nexus_user
    password: nexus_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Laisse Flyway gérer la structure, Hibernate valide uniquement
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:dGVzdC1qd3Qtc2VjcmV0LWtleS1taW5pbXVtLTMyLWNoYXJhY3RlcnMtbG9uZw==}
    encryption:
      secret-key: ${ENCRYPTION_SECRET_KEY:dummy-key-32-bytes-long-exactly!}

nexus:
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY:}
  storage:
    path: d:/Dev/NEXUS/storage