spring:
  application:
    name: nexus-erp

  datasource:
    url: jdbc:h2:mem:nexus_erp_db;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Laisse Flyway gérer la structure, Hibernate valide uniquement
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  flyway:
    enabled: true
    baseline-on-migrate: true

application:
  security:
    jwt:
      secret-key: dGhpcy1pcy1hLXZlcnktc2VjdXJlLTMyLWJ5dGUtbG9uZy1rZXktZm9yLWp3dC1zaWduaW5nLXVzaW5nLWhmYWMtMjU2LWFsZ29yaXRobQ==